
USE CAOFRADES_FC

SELECT J.ID_JOGADOR, P.NOME AS NOME, P.APELIDO AS APELIDO, PJ.DESCRICAO AS POSICAO, SJ.DESCRICAO AS STATUS_JOGADOR FROM TBL_JOGADOR J
	JOIN TBL_PESSOA P ON J.ID_PESSOA = P.ID_PESSOA
	JOIN TBL_POSICAO_JOGADOR PJ ON J.ID_POSICAO = PJ.ID_POSICAO_JOGADOR
	JOIN TBL_STATUS_JOGADOR SJ ON J.ID_STATUS_JOGADOR = SJ.ID_STATUS_JOGADOR AND SJ.ID_STATUS_JOGADOR = 1


-- RESETAR IDENTITY

	DBCC CHECKIDENT ('TBL_LOCAL_JOGO', RESEED, 0) 