-- SCRIPT INSERÇÃO DE JOGOS

USE CAOFRADES_FC

SELECT * FROM TBL_JOGOS
SELECT * FROM TBL_PESSOA
SELECT * FROM TBL_TIPO_JOGO
SELECT * FROM TBL_LOCAL_JOGO
SELECT * FROM TBL_PONTO_ENCONTRO

DECLARE @VITORIA INT, @EMPATE INT, @DERROTA INT, @JOGO_EM_CASA INT, @JOGO_FORA INT, @UNIFORME_UM INT, @AMISTOSO INT, @CAMP_1 INT, @CAMP_2 INT

SET @VITORIA = (SELECT R.ID_RESULTADO_JOGO FROM TBL_RESULTADO_JOGO R WHERE R.RESULTADO = 'Vitória')
SET @EMPATE = (SELECT R.ID_RESULTADO_JOGO FROM TBL_RESULTADO_JOGO R WHERE R.RESULTADO = 'Empate')
SET @DERROTA = (SELECT R.ID_RESULTADO_JOGO FROM TBL_RESULTADO_JOGO R WHERE R.RESULTADO = 'Derrota')

SET @JOGO_EM_CASA = 1
SET @JOGO_FORA = 0

SET @AMISTOSO = (SELECT TJ.ID_TIPO_JOGO FROM TBL_TIPO_JOGO TJ WHERE TJ.DESCRICAO = 'Amistoso')
SET @CAMP_1 = (SELECT TJ.ID_TIPO_JOGO FROM TBL_TIPO_JOGO TJ WHERE TJ.DESCRICAO = '1a Copa União Acabamentos/MS Calçados de Futebol Suiço Livre')
SET @CAMP_2 = (SELECT TJ.ID_TIPO_JOGO FROM TBL_TIPO_JOGO TJ WHERE TJ.DESCRICAO = '2a Copa União Acabamentos/MS Calçados de Futebol Suiço Livre')

SET @UNIFORME_UM = (SELECT U.ID_UNIFORME FROM TBL_UNIFORME U WHERE U.DESCRICAO = 'Uniforme 1')

INSERT INTO TBL_JOGOS
	VALUES
		('2017-02-05 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Venda dos Pretos'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Odirley'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-02-12 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Boa Esperança'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Hélio'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-02-19 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara da Marli'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Cirilo'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, 'Partida interrompida aos 10 minutos do 2º tempo por causa de briga'),

		('2017-02-26 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Campo Viação Velha'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Beto'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-03-05 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Venda dos Pretos'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Douglas'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-03-12 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Campo Viação Velha'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do César'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-03-19 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Terminal do Acapulco'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Toca do Jacaré'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Celso'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-03-26 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Boa Esperança'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do José Clodoaldo'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-04-02 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Praça do Tiro de Guerra'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'ACEL'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Dilson'),
		@EMPATE, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-04-09 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Posto Mediterrâneo'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'GREPOM'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Roberto'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-04-23 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Boa Esperança'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Hélio'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-04-30 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Venda dos Pretos'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Odirley'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-05-07 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Bar do Ary'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Campo Jd. Alpes'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Daniel'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-05-14 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Terminal do Vivi Xavier'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Santa Úrsula'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Paulo'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-05-28 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Campo Viação Velha'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Beto'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-06-04 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Supermercado 88'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara 3 Figueiras'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Jean'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-06-11 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Terminal do Acapulco'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Baixada Santista'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Iury'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-06-18 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Campo Viação Velha'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do César'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-06-25 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Praça do Tiro de Guerra'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'ACEL'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Dilson'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-07-02 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Terminal do Acapulco'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Toca do Jacaré'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Celso'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-07-09 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara do Belinati'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Adílson'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-07-16 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Posto Mediterrâneo'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'GREPOM'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Roberto'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-07-23 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Feira Livre do Cafezal'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Baixada Santista'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Ferreira'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-07-30 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Boa Esperança'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do José Clodoaldo'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-08-06 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = '5o Batalhão da Polícia Militar'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = '5o Batalhão da Polícia Militar'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Ribeiro'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-08-13 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Boa Esperança'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Hélio'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-08-20 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Posto Sun Lake'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Boa Esperança'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Hélio'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-08-27 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Campo Viação Velha'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Beto'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-09-03 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Terminal do Vivi Xavier'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Santa Úrsula'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Paulo'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-09-10 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara do caseiro Amarildo'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do João Felipe'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-09-24 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Boa Esperança'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Peterson'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-10-01 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara do caseiro Amarildo'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Luciano'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-10-15 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Venda dos Pretos'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Odirley'),
		@EMPATE, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-10-22 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Terminal do Vivi Xavier'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Dom Bosco'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Douglas'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-10-29 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Campo Viação Velha'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do César'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-11-05 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Supermercado 88'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Rondopar'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Roger'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-11-12 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Bar do Ary'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Campo Jd. Alpes'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Daniel'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-11-19 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Terminal do Vivi Xavier'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Retiro dos Cansados'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Otacílio'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-11-26 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Grêmio Esportivo Cacique'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Nissei'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Wesley'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-12-03 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Recanto das Tulipas'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Kelvin'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-12-17 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Terminal do Acapulco'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Baixada Santista'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Ronaldo'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		-- CONTINUAR A PARTIR DA PARTIDA 42