--SCRIPT MIGRAÇÃO JOGADOR POSICAO
USE CAOFRADES_FC

SELECT * FROM TBL_JOGADOR

SELECT * FROM TBL_POSICAO_JOGADOR

DECLARE @GOLEIRO INT, @ZAGUEIRO INT, @LATERAL INT, @VOLANTE INT, @MEIA INT, @ATACANTE INT

SET @GOLEIRO = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Goleiro')
SET @ZAGUEIRO = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Zagueiro')
SET @LATERAL = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Lateral')
SET @VOLANTE = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Volante')
SET @MEIA = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Meia')
SET @ATACANTE = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Atacante')

INSERT INTO TBL_JOGADOR 
	VALUES
	(NULL, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gabriel Deliberador'), @GOLEIRO),
	(NULL, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Tamarozzi'), @GOLEIRO),
	(NULL, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Kléber'), @GOLEIRO),
	(NULL, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Matheus Henrique'), @GOLEIRO),
	(NULL, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Fábio'), @GOLEIRO),
	(NULL, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Luiz Felipe'), @GOLEIRO),
	(NULL, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Kauan'), @GOLEIRO),
	(NULL, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gil'), @GOLEIRO),
	(NULL, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Felipe Deliberador'), @GOLEIRO),