--SCRIPT MIGRAÇÃO JOGADOR POSICAO
USE CAOFRADES_FC

DECLARE @GOLEIRO INT, @ZAGUEIRO INT, @LATERAL INT, @VOLANTE INT, @MEIA INT, @ATACANTE INT, @JOGADOR INT, @TAMPAO INT, @EX_JOGADOR INT

SET @JOGADOR = (SELECT S.ID_STATUS_JOGADOR FROM TBL_STATUS_JOGADOR S WHERE DESCRICAO = 'Jogador')
SET @TAMPAO = (SELECT S.ID_STATUS_JOGADOR FROM TBL_STATUS_JOGADOR S WHERE DESCRICAO = 'Tampão')
SET @EX_JOGADOR = (SELECT S.ID_STATUS_JOGADOR FROM TBL_STATUS_JOGADOR S WHERE DESCRICAO = 'Ex-jogador')

SET @GOLEIRO = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Goleiro')
SET @ZAGUEIRO = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Zagueiro')
SET @LATERAL = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Lateral')
SET @VOLANTE = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Volante')
SET @MEIA = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Meia')
SET @ATACANTE = (SELECT P.ID_POSICAO_JOGADOR FROM TBL_POSICAO_JOGADOR P WHERE P.DESCRICAO = 'Atacante')

INSERT INTO TBL_JOGADOR 
	VALUES
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gabriel Deliberador'), @GOLEIRO, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Tamarozzi'), @GOLEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Kléber'), @GOLEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Matheus Henrique'), @GOLEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Fábio'), @GOLEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Luiz Felipe'), @GOLEIRO, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Kauan'), @GOLEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gil'), @GOLEIRO, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Felipe Deliberador'), @GOLEIRO, @TAMPAO),

	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gustavo'), @ZAGUEIRO, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gabriel Saito'), @ZAGUEIRO, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Geovane'), @ZAGUEIRO, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Diogo'), @ZAGUEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Eduardo'), @ZAGUEIRO, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Alison Júnior'), @ZAGUEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Bruno'), @ZAGUEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Guilherme Rocha'), @ZAGUEIRO, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Juninho'), @ZAGUEIRO, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Jéfferson Roncaratti'), @ZAGUEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Joab'), @ZAGUEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Leonardo Barbosa'), @ZAGUEIRO, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Fabrício'), @ZAGUEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Luis Guilherme'), @ZAGUEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Herek'), @ZAGUEIRO, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Geremias'), @ZAGUEIRO, @EX_JOGADOR),

	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Diego Rocha'), @LATERAL, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Laércio'), @LATERAL, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Edson'), @LATERAL, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Vitor Guimarães'), @LATERAL, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Jão'), @LATERAL, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Álex'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Giovani'), @LATERAL, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Diego Marques'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Mizael'), @LATERAL, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Vinicius'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Danilo Canhim'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Borges'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Mateus Rocha'), @LATERAL, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Kauê'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Geovany Roncaratti'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Luiz Gustavo Nunes'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Thiago'), @LATERAL, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Rafael Aboriham'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Thiago Jacob'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Vinicius Deliberador'), @LATERAL, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Michael Robles'), @LATERAL, @EX_JOGADOR),

	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Jefferson Bachega'), @VOLANTE, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Júlio Pelógia'), @VOLANTE, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Flavio'), @VOLANTE, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Diego'), @VOLANTE, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Du'), @VOLANTE,@TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Kbça'), @VOLANTE, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Cassa'), @VOLANTE, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Lucas Machado'), @VOLANTE, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Rafael'), @VOLANTE, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Renato'), @VOLANTE, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Felipe'), @VOLANTE, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gerlan'), @VOLANTE, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Lucas Manganari'), @VOLANTE, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Guilherme Crotti'), @VOLANTE, @EX_JOGADOR),

	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Matheus Polo'), @MEIA, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Rodrigo Paiva'), @MEIA, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Thiago Kanazawa'), @MEIA, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Luis Felipe'), @MEIA, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Mateus'), @MEIA, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Lucas'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gui'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gabriel'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'João Gustavo'), @MEIA, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Bonel'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Baiano'), @MEIA, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Wagner'), @MEIA,@TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'João Vitor'), @MEIA,@EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Neto'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Diego Milani'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Lucas Gustavo'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Matheus Santana'), @MEIA, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Cézar'), @MEIA, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'João Alexandre'), @MEIA,@TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Léo'), @MEIA, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Pato'), @MEIA, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Duda'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Álvaro'), @MEIA, @EX_JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Lucas Andrade'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Gustavo Cogo'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Matheus Figueiredo'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Wellyton'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Rafael Dutra'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Rogério'), @MEIA, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Fernando'), @MEIA, @TAMPAO),

	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Danilo Hara'), @ATACANTE, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Iratan Pedro Rugila'), @ATACANTE, @JOGADOR),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Nicolas'), @ATACANTE, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Thiago Chaves'), @ATACANTE, @TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Lucas Azevedo'), @ATACANTE,@TAMPAO),
	(99, (SELECT ID_PESSOA FROM TBL_PESSOA WHERE NOME = 'Matheus Ribeiro'), @ATACANTE,@TAMPAO);

