-- SCRIPT INSERÇÃO DE JOGOS

SELECT * FROM TBL_JOGOS
SELECT * FROM TBL_PESSOA
SELECT * FROM TBL_TIPO_JOGO
SELECT * FROM TBL_LOCAL_JOGO

DECLARE @VITORIA INT, @EMPATE INT, @DERROTA INT, @JOGO_EM_CASA INT, @JOGO_FORA INT, @UNIFORME_UM INT, @AMISTOSO INT, @CAMP_1 INT, @CAMP_2 INT

SET @VITORIA = (SELECT R.ID_RESULTADO_JOGO FROM TBL_RESULTADO_JOGO R WHERE R.RESULTADO = 'Vitória')
SET @EMPATE = (SELECT R.ID_RESULTADO_JOGO FROM TBL_RESULTADO_JOGO R WHERE R.RESULTADO = 'Empate')
SET @DERROTA = (SELECT R.ID_RESULTADO_JOGO FROM TBL_RESULTADO_JOGO R WHERE R.RESULTADO = 'Derrota')

SET @JOGO_EM_CASA = 1
SET @JOGO_FORA = 0

SET @AMISTOSO = (SELECT TJ.ID_TIPO_JOGO FROM TBL_TIPO_JOGO TJ WHERE TJ.DESCRICAO = 'Amistoso')
SET @CAMP_1 = (SELECT TJ.ID_TIPO_JOGO FROM TBL_TIPO_JOGO TJ WHERE TJ.DESCRICAO = '1a Copa União Acabamentos/MS Calçados de Futebol Suiço Livre')
SET @CAMP_2 = (SELECT TJ.ID_TIPO_JOGO FROM TBL_TIPO_JOGO TJ WHERE TJ.DESCRICAO = '2a Copa União Acabamentos/MS Calçados de Futebol Suiço Livre')

SET @UNIFORME_UM = (SELECT U.ID_UNIFORME FROM TBL_UNIFORME U WHERE U.DESCRICAO = 'Uniforme 1')

INSERT INTO TBL_JOGOS
	VALUES
		('2017-02-05 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Venda dos Pretos'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Odirley'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-02-12 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara Boa Esperança'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Hélio'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-02-19 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Chácara da Marli'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Cirilo'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, 'Partida interrompida aos 10 minutos do 2º tempo por causa de briga'),

		('2017-02-26 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Campo Viação Velha'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Beto'),
		@VITORIA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		('2017-03-05 09:30:00.000', 
		(SELECT PE.ID_PONTO_ENCONTRO FROM TBL_PONTO_ENCONTRO PE WHERE PE.DESCRICAO = 'Villa 10'),
		(SELECT LJ.ID_LOCAL_JOGO FROM TBL_LOCAL_JOGO LJ WHERE LJ.DESCRICAO = 'Venda dos Pretos'),
		(SELECT A.ID_ADVERSARIO FROM TBL_ADVERSARIO A WHERE A.NOME = 'Time do Douglas'),
		@DERROTA, @UNIFORME_UM, @AMISTOSO, NULL, @JOGO_FORA, NULL),

		--CONTINUAR A PARTIR DO JOGO 6