--SCRIPT MIGRAÇÃO CONTENDO TODAS AS PESSOAS QUE JÁ JOGARAM PELO CAOFRADES
USE CAOFRADES_FC

INSERT INTO TBL_PESSOA 
	VALUES
		('Danilo Hara', 'Hara', GETDATE()),
		('Iratan Pedro Rugila', 'Iratan', GETDATE()),
		('Diego Rocha', 'Rocha', GETDATE()),
		('Rodrigo Paiva', 'Paiva', GETDATE()),
		('Michael Robles', 'Neguin', GETDATE()),
		('Lucas Manganari', 'Manga', GETDATE()),
		('Gil', NULL, GETDATE()),
		('Thiago Kanazawa', 'Kana', GETDATE()),
		('Cézar', NULL, GETDATE()),
		('Luiz Felipe', 'Babugia', GETDATE()),
		('Gustavo', NULL, GETDATE()),
		('Matheus Polo', 'Polo', GETDATE()),
		('Juninho', NULL, GETDATE()),
		('Thiago', NULL, GETDATE()),
		('Álvaro', NULL, GETDATE()),
		('Júlio Pelógia', 'Lindo', GETDATE()),
		('Léo', NULL, GETDATE()),
		('Laércio', NULL, GETDATE()),
		('Matheus Santana', NULL, GETDATE()),
		('Gabriel Deliberador', 'Paredão', GETDATE()),
		('Luis Felipe', 'Arão', GETDATE()),
		('Jefferson Bachega', 'Bachega', GETDATE()),
		('Guilherme Crotti', 'Crotti', GETDATE()),
		('Guilherme Rocha', NULL, GETDATE()),
		('Eduardo', NULL, GETDATE()),
		('Gustavo Cogo', 'Cogo', GETDATE()),
		('Leonardo Barbosa', NULL, GETDATE()),
		('Edson', 'Mentira', GETDATE()),
		('Geremias', 'Geremito', GETDATE()),
		('Cassa', NULL, GETDATE()),
		('Gabriel Saito', 'Saito', GETDATE()),
		('Geovany Roncaratti', 'Geovany', GETDATE()),
		('Mateus Rocha', NULL, GETDATE()),
		('Lucas Machado', NULL, GETDATE()),
		('Mizael', 'Miza', GETDATE()),
		('Giovani', NULL, GETDATE()),
		('Jéfferson Roncaratti', 'Jé', GETDATE()),
		('João Vitor', NULL, GETDATE()),
		('Jão', NULL, GETDATE()),
		('Vitor Guimarães', 'Batata', GETDATE()),
		('Pato', NULL, GETDATE()),
		('João Gustavo', NULL, GETDATE()),
		('Kauê', NULL, GETDATE()),
		('Baiano', NULL, GETDATE()),
		('Kbça', NULL, GETDATE()),
		('Geovane', NULL, GETDATE()),
		('Borges', NULL, GETDATE()),
		('Thiago Jacob', 'Jacob', GETDATE()),
		('Kauan', NULL, GETDATE()),
		('Fabrício', NULL, GETDATE()),
		('Du', NULL, GETDATE()),
		('Matheus Figueiredo', NULL, GETDATE()),
		('Renato', NULL, GETDATE()),
		('Mateus', NULL, GETDATE()),
		('Luiz Gustavo Nunes', NULL, GETDATE()),
		('Lucas', NULL, GETDATE()),
		('Lucas Azevedo', NULL, GETDATE()),
		('Gui', NULL, GETDATE()),
		('Gabriel', NULL, GETDATE()),
		('Tamarozzi', NULL, GETDATE()),
		('Flavio', NULL, GETDATE()),
		('Álex', NULL, GETDATE()),
		('Bonel', NULL, GETDATE()),
		('Diego', NULL, GETDATE()),
		('Wagner', NULL, GETDATE()),
		('Diego Marques', NULL, GETDATE()),
		('Diogo', NULL, GETDATE()),
		('Neto', NULL, GETDATE()),
		('Alison Júnior', NULL, GETDATE()),
		('Vinicius', NULL, GETDATE()),
		('Danilo Canhim', NULL, GETDATE()),
		('Nicolas', NULL, GETDATE()),
		('Diego Milani', NULL, GETDATE()),
		('Kléber', NULL, GETDATE()),
		('Bruno', NULL, GETDATE()),
		('Rafael', NULL, GETDATE()),
		('Lucas Gustavo', NULL, GETDATE()),
		('Matheus Henrique', NULL, GETDATE()),
		('João Alexandre', NULL, GETDATE()),
		('Fábio', NULL, GETDATE()),
		('Felipe', NULL, GETDATE()),
		('Duda', NULL, GETDATE()),
		('Lucas Andrade', NULL, GETDATE()),
		('Thiago Chaves', NULL, GETDATE()),
		('Joab', NULL, GETDATE()),
		('Rafael Aboriham', NULL, GETDATE()),
		('Felipe Deliberador', NULL, GETDATE()),
		('Gerlan', NULL, GETDATE()),
		('Vinicius Deliberador', NULL, GETDATE()),
		('Wellyton', NULL, GETDATE()),
		('Rafael Dutra', NULL, GETDATE()),
		('Luis Guilherme', NULL, GETDATE()),
		('Matheus Ribeiro', NULL, GETDATE()),
		('Herek', NULL, GETDATE()),
		('Rogério', NULL, GETDATE()),
		('Fernando', NULL, GETDATE());